version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/restaurant-reservation
    networks:
      - app-network
    command: sh -c "node scripts/seedData.js && npm start"

networks:
  app-network:
    driver: bridge
